### ISSUE TITLE
Can't detect multi key event correctly.

### ISSUE THREAD

**Issue by xiaohuirong** [ellbur/totalmapper#14]
For example, when I play game, I want to press W and D to move to upper right or press W and SPACE to move forward and jump, but just one key take effect.

**Comment by ellbur** [comment]
Thanks for pointing this out. I will take a look.

Can you provide the JSON for the key mappings you are using?

**Comment by ellbur** [comment]
OK I think I found what was going on. This was a semi-intentional feature, but it I think it can be changed.

The issue has to do with mappings that result in modifiers. For example, to map <kbd>A</kbd> to <kbd>+</kbd>, you would map it to <kbd>Shift</kbd>+<kbd>=</kbd>.

The problem is that if you then press, say, <kbd>1</kbd>, you get <kbd>!</kbd> because <kbd>Shift</kbd> is still down. 

Now you might say, just release the <kbd>Shift</kbd> and leave <kbd>=</kbd> down. The problem is, this can result in a momentary unshifted <kbd>=</kbd>, which is undesirable. In order to compensate for this, `totalmapper` releases *all* non-modifier keys every time a new one has pressed.

However, as you point out, this has undesirable consequences. Some software (such as games) interprets combinations of keys that are not modifiers. 

So I think the solution is to make it only release key combinations that include at least one modifier.

**Comment by ellbur** [comment]
Should be fixed in the latest release.

**Comment by xiaohuirong** [comment]
I have tried xmodmap and xkb, they aren't perfect. Keymap problem really bother me until I found this tool. Thank for writing this tool, It's greatly helpful for me. Hope this problem can be solved. Here is my json file  content.
```json
{
  "mappings": [
    { "from": [ "RIGHTALT", "A" ], "to": [ "LEFT" ] },
    { "from": [ "RIGHTALT", "W" ], "to": [ "UP" ] },
    { "from": [ "RIGHTALT", "S" ], "to": [ "DOWN" ] },
    { "from": [ "RIGHTALT", "D" ], "to": [ "RIGHT" ] },
    { "from": [ "RIGHTALT", "E" ], "to": [ "ENTER" ] },
    { "from": [ "RIGHTALT", "X" ], "to": [ "BACKSPACE" ] },
    { "from": [ "RIGHTALT", "F" ], "to": [ "HOME" ] },
    { "from": [ "RIGHTALT", "G" ], "to": [ "END" ] },
    { "from": [ "ESC" ], "to": [ "ESC" ], "repeat": "Disabled" },
    { "from": [ "ESC", "H" ], "to": [ "1" ] },
    { "from": [ "ESC", "J" ], "to": [ "2" ] },
    { "from": [ "ESC", "K" ], "to": [ "3" ] },
    { "from": [ "ESC", "L" ], "to": [ "4" ] },
    { "from": [ "ESC", "SEMICOLON" ], "to": [ "5" ] },
    { "from": [ "ESC", "Y" ], "to": [ "6" ] },
    { "from": [ "ESC", "U" ], "to": [ "7" ] },
    { "from": [ "ESC", "I" ], "to": [ "8" ] },
    { "from": [ "ESC", "O" ], "to": [ "9" ] },
    { "from": [ "ESC", "P" ], "to": [ "0" ] },
    { "from": [ "ESC", "M" ], "to": [ "BACKSPACE" ] },
    
    { "from": [ "COMPOSE" ], "to": [] },
    { "from": [ "COMPOSE", "A" ], "to": [ "1" ] },
    { "from": [ "COMPOSE", "S" ], "to": [ "2" ] },
    { "from": [ "COMPOSE", "D" ], "to": [ "3" ] },
    { "from": [ "COMPOSE", "F" ], "to": [ "4" ] },
    { "from": [ "COMPOSE", "G" ], "to": [ "5" ] },
    { "from": [ "COMPOSE", "Q" ], "to": [ "6" ] },
    { "from": [ "COMPOSE", "W" ], "to": [ "7" ] },
    { "from": [ "COMPOSE", "E" ], "to": [ "8" ] },
    { "from": [ "COMPOSE", "R" ], "to": [ "9" ] },
    { "from": [ "COMPOSE", "T" ], "to": [ "0" ] },
    { "from": [ "COMPOSE", "X" ], "to": [ "BACKSPACE" ] }
  ]
}
```

**Comment by xiaohuirong** [comment]
v1.3.14 works fine. A great job😄
