### ISSUE TITLE
Support for Umlauts

### ISSUE THREAD

**Issue by uestueab** [ellbur/totalmapper#6]
Hey, any chance for you to support umlauts? I was looking in names in https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h but since i can find them, i assume totalmapper wont work umlauts.

**Comment by ellbur** [comment]
Hi, great question.

`totalmapper` by itself cannot do umlauts because `totalmapper` only works with keycodes, not symbols. 

The mapping between keycodes and symbols is handled in your keyboard layout. If you are on Linux using X, your keyboard layout is handled using a system called [`xkb`](https://wiki.archlinux.org/title/X_keyboard_extension). If you are using Wayland, the keyboard layout is still written in `xkb` format, but you will have to read the docs for your specific Wayland compositor to see how to configure it.

So, if you want to type umlauts, you can edit your keyboard layout to include them. The [ArchWiki page](https://wiki.archlinux.org/title/X_keyboard_extension) has decent examples showing how to do that.

**Comment by ellbur** [comment]
I added a description to the README which should hopefully clarify how to use non-English symbols.
